-- the first script for migration
create table User (
    id bigint generated by default as identity,
    fullname varchar(255),
    isAdmin boolean not null,
    password varchar(255),
    username varchar(255),
    primary key (id)
);